Database scheme required for ci-web and jenkins
===============================================

https://github.com/ci-rt/ci-web[ci-web] and
https://github.com/ci-rt/jenkins[Jenkins] use a database to show and
to store the test results.

Prerequisites
-------------

postgreql-9.5 or higher is required, because the feature "row level
security" is used. postgresql-9.6 is a LTS version.



Configure
---------

First, a data base RT-Test needs to be created. Therefore change the user to
postgres and execute the _createdb_ command:

----
su - postgres
createdb RT-Test
----

Create nessessary database roles "jenkins" for injection and
"consumer" for reading access. Run _createuser_ to as user postgres
achieve this and set passwords as desired:

----
createuser -E -l -P jenkins
createuser -E -l -P consumer
----


After this, the data base scheme needs to be inserted into the created data
base:

----
psql RT-Test < /PATH/TO/CI-WEB/GIT/REPO/RT-Test.psql
----

Change owner of a dataset
-------------------------
To update the owner of a dataset of a specific test run, execute the
update_owner script:

---
$ update_owner -u jenkins 4711 new_owner
UPDATE 1
UPDATE 1
UPDATE 1
UPDATE 2
---

---
$ update_owner -h
CI-RT - update_owner

Usage: update_owner [options] SCHEDULER_ID OWNER
Options:
     -h,     --help          print this message
     -H,     --host          database host
     -n,     --no-action     Dry run. No database action is actually taken.
	                     Instead print out the actual SQL statement.
     -u,     --user          database user
     -v,     --verbose       Make the script verbose
---
