--
-- PostgreSQL database dump
--

-- Dumped from database version 9.6.1
-- Dumped by pg_dump version 9.6.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

SET search_path = public, pg_catalog;

DROP POLICY IF EXISTS jenkins_all ON minavgmax;
DROP POLICY IF EXISTS jenkins_all ON histogram;
DROP POLICY IF EXISTS jenkins_all ON git;
DROP POLICY IF EXISTS jenkins_all ON cyclictest;
DROP POLICY IF EXISTS jenkins_all ON compiletest;
DROP POLICY IF EXISTS jenkins_all ON boottest;
DROP POLICY IF EXISTS jenkins_all ON cirtbranch;
DROP POLICY IF EXISTS jenkins_all ON cirtscheduler;
DROP POLICY IF EXISTS consumer_view ON cirtscheduler;
DROP POLICY IF EXISTS consumer_view ON histogram;
DROP POLICY IF EXISTS consumer_view ON git;
DROP POLICY IF EXISTS consumer_view ON cyclictest;
DROP POLICY IF EXISTS consumer_view ON compiletest;
DROP POLICY IF EXISTS consumer_view ON boottest;
ALTER TABLE IF EXISTS ONLY public.target DROP CONSTRAINT IF EXISTS target_label_id_fkey;
ALTER TABLE IF EXISTS ONLY public.tags DROP CONSTRAINT IF EXISTS tags_git_id_fkey;
ALTER TABLE IF EXISTS ONLY public.minavgmax DROP CONSTRAINT IF EXISTS minavgmax_cyclictest_id_fkey;
ALTER TABLE IF EXISTS ONLY public.histogram DROP CONSTRAINT IF EXISTS histogram_cyclictest_id_fkey;
ALTER TABLE IF EXISTS ONLY public.cyclictest DROP CONSTRAINT IF EXISTS cyclictest_boottest_id_fkey;
ALTER TABLE IF EXISTS ONLY public.compiletest DROP CONSTRAINT IF EXISTS compiletest_cirtscheduler_id_fkey;
ALTER TABLE IF EXISTS ONLY public.cirtscheduler DROP CONSTRAINT IF EXISTS cirtscheduler_commit_fkey;
ALTER TABLE IF EXISTS ONLY public.cirtbranch DROP CONSTRAINT IF EXISTS cirtbranch_cirtscheduler_id_fkey;
ALTER TABLE IF EXISTS ONLY public.boottest DROP CONSTRAINT IF EXISTS boottest_target_id_fkey;
ALTER TABLE IF EXISTS ONLY public.boottest DROP CONSTRAINT IF EXISTS boottest_compiletest_id_fkey;
DROP INDEX IF EXISTS public.public_histogram_cyclictest_id1_idx;
DROP INDEX IF EXISTS public.public_cyclictest_boottest_id1_idx;
DROP INDEX IF EXISTS public.public_compiletest_cirtscheduler_id1_idx;
DROP INDEX IF EXISTS public.public_boottest_target_id2_idx;
DROP INDEX IF EXISTS public.public_boottest_pass3_idx;
DROP INDEX IF EXISTS public.public_boottest_compiletest_id4_idx;
DROP INDEX IF EXISTS public.public_boottest_bootdate1_idx;
ALTER TABLE IF EXISTS ONLY public.target DROP CONSTRAINT IF EXISTS target_pkey;
ALTER TABLE IF EXISTS ONLY public.tags DROP CONSTRAINT IF EXISTS tags_pkey;
ALTER TABLE IF EXISTS ONLY public.minavgmax DROP CONSTRAINT IF EXISTS minavgmax_pkey;
ALTER TABLE IF EXISTS ONLY public.label DROP CONSTRAINT IF EXISTS label_pkey;
ALTER TABLE IF EXISTS ONLY public.histogram DROP CONSTRAINT IF EXISTS histogram_ukey;
ALTER TABLE IF EXISTS ONLY public.histogram DROP CONSTRAINT IF EXISTS histogram_pkey;
ALTER TABLE IF EXISTS ONLY public.git DROP CONSTRAINT IF EXISTS git_pkey;
ALTER TABLE IF EXISTS ONLY public.cyclictest DROP CONSTRAINT IF EXISTS cyclictest_pkey;
ALTER TABLE IF EXISTS ONLY public.compiletest DROP CONSTRAINT IF EXISTS compiletest_pkey;
ALTER TABLE IF EXISTS ONLY public.cirtscheduler DROP CONSTRAINT IF EXISTS cirtscheduler_pkey;
ALTER TABLE IF EXISTS ONLY public.cirtbranch DROP CONSTRAINT IF EXISTS cirtbranch_pkey;
ALTER TABLE IF EXISTS ONLY public.boottest DROP CONSTRAINT IF EXISTS boottest_pkey;
ALTER TABLE IF EXISTS public.target ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.tags ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.label ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.histogram ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.git ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.cyclictest ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.compiletest ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.cirtscheduler ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.boottest ALTER COLUMN id DROP DEFAULT;
DROP VIEW IF EXISTS public.targets;
DROP VIEW IF EXISTS public.targetboot;
DROP VIEW IF EXISTS public.target_tests;
DROP SEQUENCE IF EXISTS public.target_id_seq;
DROP SEQUENCE IF EXISTS public.tags_id_seq;
DROP VIEW IF EXISTS public.overview;
DROP TABLE IF EXISTS public.tags;
DROP TABLE IF EXISTS public.minavgmax;
DROP SEQUENCE IF EXISTS public.label_id_seq;
DROP VIEW IF EXISTS public.kbuild;
DROP TABLE IF EXISTS public.label;
DROP VIEW IF EXISTS public.histogram_view;
DROP SEQUENCE IF EXISTS public.histogram_id_seq;
DROP TABLE IF EXISTS public.histogram;
DROP SEQUENCE IF EXISTS public.hibernate_sequence;
DROP VIEW IF EXISTS public.git_view;
DROP SEQUENCE IF EXISTS public.git_id_seq;
DROP TABLE IF EXISTS public.git;
DROP VIEW IF EXISTS public.donut;
DROP VIEW IF EXISTS public.detail;
DROP VIEW IF EXISTS public.cyclictest_view;
DROP SEQUENCE IF EXISTS public.cyclictest_id_seq;
DROP VIEW IF EXISTS public.cyc_target;
DROP TABLE IF EXISTS public.target;
DROP TABLE IF EXISTS public.cyclictest;
DROP SEQUENCE IF EXISTS public.compiletest_id_seq;
DROP SEQUENCE IF EXISTS public.cirtscheduler_id_seq;
DROP TABLE IF EXISTS public.cirtscheduler;
DROP TABLE IF EXISTS public.cirtbranch;
DROP VIEW IF EXISTS public.build;
DROP TABLE IF EXISTS public.compiletest;
DROP VIEW IF EXISTS public.boottest_view;
DROP SEQUENCE IF EXISTS public.boottest_id_seq;
DROP TABLE IF EXISTS public.boottest;
DROP EXTENSION IF EXISTS plpgsql;
DROP SCHEMA IF EXISTS public;
--
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO postgres;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- Name: plpgsql; Type: EXTENSION; Schema: -; Owner: 
--

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;


--
-- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';


SET search_path = public, pg_catalog;

SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: boottest; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE boottest (
    id integer NOT NULL,
    cmdline character varying(1024) NOT NULL,
    pass boolean NOT NULL,
    compiletest_id integer NOT NULL,
    target_id integer NOT NULL,
    bootdate timestamp without time zone NOT NULL,
    owner text DEFAULT 'consumer'::text NOT NULL,
    notes character varying(1024),
    bootlog bytea NOT NULL
);


ALTER TABLE boottest OWNER TO postgres;

--
-- Name: boottest_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE boottest_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE boottest_id_seq OWNER TO postgres;

--
-- Name: boottest_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE boottest_id_seq OWNED BY boottest.id;


--
-- Name: boottest_view; Type: VIEW; Schema: public; Owner: consumer
--

CREATE VIEW boottest_view AS
 SELECT b.id,
    b.target_id,
    b.cmdline,
    b.pass
   FROM boottest b;


ALTER TABLE boottest_view OWNER TO consumer;

--
-- Name: compiletest; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE compiletest (
    id integer NOT NULL,
    custom_commit character varying(40),
    defconfig bytea NOT NULL,
    "overlay" character varying(45) NOT NULL,
    pass boolean NOT NULL,
    cirtscheduler_id integer NOT NULL,
    configname character varying(80) NOT NULL,
    arch character varying(20) NOT NULL,
    buildcmd bytea NOT NULL,
    owner text DEFAULT 'consumer'::text NOT NULL,
    notes character varying(1024),
    buildlog bytea NOT NULL
);


ALTER TABLE compiletest OWNER TO postgres;

--
-- Name: build; Type: VIEW; Schema: public; Owner: consumer
--

CREATE VIEW build AS
 SELECT c.id,
    c."overlay",
    c.defconfig,
    c.pass,
    c.configname AS config,
    c.buildcmd AS testscript
   FROM compiletest c;


ALTER TABLE build OWNER TO consumer;

--
-- Name: cirtbranch; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE cirtbranch (
    id integer NOT NULL,
    testbranch character varying(80) NOT NULL,
    commit character varying(40) NOT NULL,
    cirtscheduler_id integer NOT NULL,
    owner text DEFAULT 'consumer'::text NOT NULL
);


ALTER TABLE cirtbranch OWNER TO postgres;

--
-- Name: cirtscheduler; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE cirtscheduler (
    id integer NOT NULL,
    branch character varying(80) NOT NULL,
    "timestamp" timestamp without time zone NOT NULL,
    tags_id integer NOT NULL,
    pass boolean NOT NULL,
    owner text DEFAULT 'consumer'::text NOT NULL,
    notes character varying(1024),
    processing boolean DEFAULT true NOT NULL
);


ALTER TABLE cirtscheduler OWNER TO postgres;

--
-- Name: cirtscheduler_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE cirtscheduler_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE cirtscheduler_id_seq OWNER TO postgres;

--
-- Name: cirtscheduler_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE cirtscheduler_id_seq OWNED BY cirtscheduler.id;


--
-- Name: compiletest_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE compiletest_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE compiletest_id_seq OWNER TO postgres;

--
-- Name: compiletest_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE compiletest_id_seq OWNED BY compiletest.id;


--
-- Name: cyclictest; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE cyclictest (
    id integer NOT NULL,
    description character varying(80) NOT NULL,
    duration integer NOT NULL,
    "interval" integer NOT NULL,
    min integer NOT NULL,
    avg integer NOT NULL,
    max integer NOT NULL,
    boottest_id integer NOT NULL,
    pass boolean NOT NULL,
    threshold integer NOT NULL,
    testscript bytea NOT NULL,
    owner text DEFAULT 'consumer'::text NOT NULL,
    notes character varying(1024),
    testlog bytea NOT NULL
);


ALTER TABLE cyclictest OWNER TO postgres;

--
-- Name: target; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE target (
    id integer NOT NULL,
    hostname character varying(80) NOT NULL,
    shortdesc character varying(80) NOT NULL,
    description bytea NOT NULL,
    label_id integer NOT NULL,
    notes character varying(1024),
    owner text DEFAULT 'consumer'::text NOT NULL
);


ALTER TABLE target OWNER TO postgres;

--
-- Name: cyc_target; Type: VIEW; Schema: public; Owner: consumer
--

CREATE VIEW cyc_target AS
 SELECT t.shortdesc,
    c.id AS c_id
   FROM ((cyclictest c
     JOIN boottest bt ON ((c.boottest_id = bt.id)))
     JOIN target t ON ((bt.target_id = t.id)));


ALTER TABLE cyc_target OWNER TO consumer;

--
-- Name: cyclictest_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE cyclictest_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE cyclictest_id_seq OWNER TO postgres;

--
-- Name: cyclictest_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE cyclictest_id_seq OWNED BY cyclictest.id;


--
-- Name: cyclictest_view; Type: VIEW; Schema: public; Owner: consumer
--

CREATE VIEW cyclictest_view AS
 SELECT c.id,
    c.description AS load,
    c.duration,
    c."interval",
    c.min,
    c.avg,
    c.max,
    c.boottest_id,
    c.pass,
    c.threshold,
    c.testscript
   FROM cyclictest c;


ALTER TABLE cyclictest_view OWNER TO consumer;

--
-- Name: detail; Type: VIEW; Schema: public; Owner: consumer
--

CREATE VIEW detail AS
 SELECT s.id AS kernelbuild,
    b.configname AS config,
    b."overlay",
    b.pass AS b_pass,
    bt.pass AS bt_pass,
    bt.pass AS cyc_pass,
    b.id AS b_id,
    bt.id AS bt_id,
    c.id AS c_id,
    b.arch
   FROM (((cirtscheduler s
     LEFT JOIN compiletest b ON ((s.id = b.cirtscheduler_id)))
     LEFT JOIN boottest bt ON ((b.id = bt.compiletest_id)))
     LEFT JOIN cyclictest c ON ((c.boottest_id = bt.id)));


ALTER TABLE detail OWNER TO consumer;

--
-- Name: donut; Type: VIEW; Schema: public; Owner: consumer
--

CREATE VIEW donut AS
 SELECT compiletest.cirtscheduler_id AS kernelbuild_id,
    count(compiletest.pass) AS passed,
    count(compiletest.id) AS count
   FROM compiletest
  GROUP BY compiletest.cirtscheduler_id
  ORDER BY compiletest.cirtscheduler_id DESC
 LIMIT 10;


ALTER TABLE donut OWNER TO consumer;

--
-- Name: git; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE git (
    id integer NOT NULL,
    path character varying(1024) NOT NULL,
    public boolean NOT NULL,
    httprepo text,
    owner text DEFAULT 'consumer'::text NOT NULL
);


ALTER TABLE git OWNER TO postgres;

--
-- Name: git_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE git_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE git_id_seq OWNER TO postgres;

--
-- Name: git_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE git_id_seq OWNED BY git.id;


--
-- Name: git_view; Type: VIEW; Schema: public; Owner: consumer
--

CREATE VIEW git_view AS
 SELECT g.id,
    g.httprepo,
    g.path
   FROM git g;


ALTER TABLE git_view OWNER TO consumer;

--
-- Name: hibernate_sequence; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE hibernate_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE hibernate_sequence OWNER TO postgres;

--
-- Name: histogram; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE histogram (
    id integer NOT NULL,
    thread integer NOT NULL,
    latency integer NOT NULL,
    count integer NOT NULL,
    cyclictest_id integer NOT NULL,
    owner text DEFAULT 'consumer'::text NOT NULL
);


ALTER TABLE histogram OWNER TO postgres;

--
-- Name: histogram_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE histogram_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE histogram_id_seq OWNER TO postgres;

--
-- Name: histogram_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE histogram_id_seq OWNED BY histogram.id;


--
-- Name: histogram_view; Type: VIEW; Schema: public; Owner: consumer
--

CREATE VIEW histogram_view AS
 SELECT h.thread AS cpu,
    h.latency,
    h.count,
    h.cyclictest_id
   FROM histogram h;


ALTER TABLE histogram_view OWNER TO consumer;

--
-- Name: label; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE label (
    id integer NOT NULL,
    arch character varying(20) NOT NULL,
    family character varying(20) NOT NULL,
    owner text DEFAULT 'consumer'::text NOT NULL
);


ALTER TABLE label OWNER TO postgres;

--
-- Name: kbuild; Type: VIEW; Schema: public; Owner: consumer
--

CREATE VIEW kbuild AS
 SELECT s.id AS kernelbuild,
    b.arch,
    b.configname AS config,
    b."overlay",
    b.pass AS b_pass,
    bt.pass AS bt_pass,
    c.pass AS cyc_pass,
    b.id AS b_id,
    bt.id AS bt_id,
    c.id AS c_id,
    bt.target_id AS t_id,
    concat_ws(' '::text, l.arch, l.family) AS t_label
   FROM (((((cirtscheduler s
     LEFT JOIN compiletest b ON ((s.id = b.cirtscheduler_id)))
     LEFT JOIN boottest bt ON ((b.id = bt.compiletest_id)))
     LEFT JOIN cyclictest c ON ((c.boottest_id = bt.id)))
     LEFT JOIN target t ON ((bt.target_id = t.id)))
     LEFT JOIN label l ON ((t.label_id = l.id)));


ALTER TABLE kbuild OWNER TO consumer;

--
-- Name: label_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE label_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE label_id_seq OWNER TO postgres;

--
-- Name: label_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE label_id_seq OWNED BY label.id;


--
-- Name: minavgmax; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE minavgmax (
    thread integer NOT NULL,
    cyclictest_id integer NOT NULL,
    min integer NOT NULL,
    avg integer NOT NULL,
    max integer NOT NULL,
    owner text DEFAULT 'consumer'::text NOT NULL
);


ALTER TABLE minavgmax OWNER TO postgres;

--
-- Name: tags; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE tags (
    id integer NOT NULL,
    git_id integer NOT NULL,
    commit character varying(40) NOT NULL,
    name character varying(80) NOT NULL,
    owner text DEFAULT 'consumer'::text NOT NULL
);


ALTER TABLE tags OWNER TO postgres;

--
-- Name: overview; Type: VIEW; Schema: public; Owner: consumer
--

CREATE VIEW overview AS
 SELECT s.id,
    s.branch,
    s."timestamp",
    t.commit,
    t.name,
    s.id AS kernelbuild,
    s.pass,
    t.git_id,
    g.path,
    g.public
   FROM ((cirtscheduler s
     JOIN tags t ON ((s.tags_id = t.id)))
     JOIN git g ON ((t.git_id = g.id)))
  WHERE (s.processing = false);


ALTER TABLE overview OWNER TO consumer;

--
-- Name: tags_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE tags_id_seq OWNER TO postgres;

--
-- Name: tags_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE tags_id_seq OWNED BY tags.id;


--
-- Name: target_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE target_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE target_id_seq OWNER TO postgres;

--
-- Name: target_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE target_id_seq OWNED BY target.id;


--
-- Name: target_tests; Type: VIEW; Schema: public; Owner: consumer
--

CREATE VIEW target_tests AS
 SELECT c.id AS c_id,
    s.branch,
    t.name,
    t.commit,
    s."timestamp",
    b.configname AS config,
    b."overlay",
    s.id AS kernelbuild,
    bt.target_id AS t_id,
    c.min AS c_min,
    c.avg AS c_avg,
    c.max AS c_max,
    c.pass
   FROM ((((cirtscheduler s
     JOIN tags t ON ((s.tags_id = t.id)))
     JOIN compiletest b ON ((s.id = b.cirtscheduler_id)))
     JOIN boottest bt ON ((b.id = bt.compiletest_id)))
     JOIN cyclictest c ON ((c.boottest_id = bt.id)));


ALTER TABLE target_tests OWNER TO consumer;

--
-- Name: targetboot; Type: VIEW; Schema: public; Owner: consumer
--

CREATE VIEW targetboot AS
 SELECT b.id,
    b.compiletest_id AS build_id,
    t.shortdesc,
    b.bootdate,
    b.cmdline,
    b.pass
   FROM (boottest b
     JOIN target t ON ((b.target_id = t.id)));


ALTER TABLE targetboot OWNER TO consumer;

--
-- Name: targets; Type: VIEW; Schema: public; Owner: consumer
--

CREATE VIEW targets AS
 SELECT concat_ws(' '::text, l.arch, l.family) AS label,
    t.shortdesc AS descr,
    t.id AS t_id
   FROM (target t
     JOIN label l ON ((t.label_id = l.id)));


ALTER TABLE targets OWNER TO consumer;

--
-- Name: boottest id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY boottest ALTER COLUMN id SET DEFAULT nextval('boottest_id_seq'::regclass);


--
-- Name: cirtscheduler id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY cirtscheduler ALTER COLUMN id SET DEFAULT nextval('cirtscheduler_id_seq'::regclass);


--
-- Name: compiletest id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY compiletest ALTER COLUMN id SET DEFAULT nextval('compiletest_id_seq'::regclass);


--
-- Name: cyclictest id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY cyclictest ALTER COLUMN id SET DEFAULT nextval('cyclictest_id_seq'::regclass);


--
-- Name: git id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY git ALTER COLUMN id SET DEFAULT nextval('git_id_seq'::regclass);


--
-- Name: histogram id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY histogram ALTER COLUMN id SET DEFAULT nextval('histogram_id_seq'::regclass);


--
-- Name: label id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY label ALTER COLUMN id SET DEFAULT nextval('label_id_seq'::regclass);


--
-- Name: tags id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY tags ALTER COLUMN id SET DEFAULT nextval('tags_id_seq'::regclass);


--
-- Name: target id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY target ALTER COLUMN id SET DEFAULT nextval('target_id_seq'::regclass);


--
-- Name: boottest boottest_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY boottest
    ADD CONSTRAINT boottest_pkey PRIMARY KEY (id);


--
-- Name: cirtbranch cirtbranch_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY cirtbranch
    ADD CONSTRAINT cirtbranch_pkey PRIMARY KEY (id, testbranch);


--
-- Name: cirtscheduler cirtscheduler_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY cirtscheduler
    ADD CONSTRAINT cirtscheduler_pkey PRIMARY KEY (id);


--
-- Name: compiletest compiletest_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY compiletest
    ADD CONSTRAINT compiletest_pkey PRIMARY KEY (id);


--
-- Name: cyclictest cyclictest_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY cyclictest
    ADD CONSTRAINT cyclictest_pkey PRIMARY KEY (id);


--
-- Name: git git_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY git
    ADD CONSTRAINT git_pkey PRIMARY KEY (id);


--
-- Name: histogram histogram_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY histogram
    ADD CONSTRAINT histogram_pkey PRIMARY KEY (id);


--
-- Name: histogram histogram_ukey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY histogram
    ADD CONSTRAINT histogram_ukey UNIQUE (thread, latency, cyclictest_id);


--
-- Name: label label_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY label
    ADD CONSTRAINT label_pkey PRIMARY KEY (id);


--
-- Name: minavgmax minavgmax_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY minavgmax
    ADD CONSTRAINT minavgmax_pkey PRIMARY KEY (cyclictest_id, thread);


--
-- Name: tags tags_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY tags
    ADD CONSTRAINT tags_pkey PRIMARY KEY (id);


--
-- Name: target target_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY target
    ADD CONSTRAINT target_pkey PRIMARY KEY (id);


--
-- Name: public_boottest_bootdate1_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX public_boottest_bootdate1_idx ON boottest USING btree (bootdate);


--
-- Name: public_boottest_compiletest_id4_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX public_boottest_compiletest_id4_idx ON boottest USING btree (compiletest_id);


--
-- Name: public_boottest_pass3_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX public_boottest_pass3_idx ON boottest USING btree (pass);


--
-- Name: public_boottest_target_id2_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX public_boottest_target_id2_idx ON boottest USING btree (target_id);


--
-- Name: public_compiletest_cirtscheduler_id1_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX public_compiletest_cirtscheduler_id1_idx ON compiletest USING btree (cirtscheduler_id);


--
-- Name: public_cyclictest_boottest_id1_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX public_cyclictest_boottest_id1_idx ON cyclictest USING btree (boottest_id);


--
-- Name: public_histogram_cyclictest_id1_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX public_histogram_cyclictest_id1_idx ON histogram USING btree (cyclictest_id);


--
-- Name: boottest boottest_compiletest_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY boottest
    ADD CONSTRAINT boottest_compiletest_id_fkey FOREIGN KEY (compiletest_id) REFERENCES compiletest(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: boottest boottest_target_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY boottest
    ADD CONSTRAINT boottest_target_id_fkey FOREIGN KEY (target_id) REFERENCES target(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: cirtbranch cirtbranch_cirtscheduler_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY cirtbranch
    ADD CONSTRAINT cirtbranch_cirtscheduler_id_fkey FOREIGN KEY (cirtscheduler_id) REFERENCES cirtscheduler(id);


--
-- Name: cirtscheduler cirtscheduler_commit_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY cirtscheduler
    ADD CONSTRAINT cirtscheduler_commit_fkey FOREIGN KEY (tags_id) REFERENCES tags(id);


--
-- Name: compiletest compiletest_cirtscheduler_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY compiletest
    ADD CONSTRAINT compiletest_cirtscheduler_id_fkey FOREIGN KEY (cirtscheduler_id) REFERENCES cirtscheduler(id);


--
-- Name: cyclictest cyclictest_boottest_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY cyclictest
    ADD CONSTRAINT cyclictest_boottest_id_fkey FOREIGN KEY (boottest_id) REFERENCES boottest(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: histogram histogram_cyclictest_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY histogram
    ADD CONSTRAINT histogram_cyclictest_id_fkey FOREIGN KEY (cyclictest_id) REFERENCES cyclictest(id);


--
-- Name: minavgmax minavgmax_cyclictest_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY minavgmax
    ADD CONSTRAINT minavgmax_cyclictest_id_fkey FOREIGN KEY (cyclictest_id) REFERENCES cyclictest(id);


--
-- Name: tags tags_git_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY tags
    ADD CONSTRAINT tags_git_id_fkey FOREIGN KEY (git_id) REFERENCES git(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: target target_label_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY target
    ADD CONSTRAINT target_label_id_fkey FOREIGN KEY (label_id) REFERENCES label(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: boottest; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE boottest ENABLE ROW LEVEL SECURITY;

--
-- Name: cirtbranch; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE cirtbranch ENABLE ROW LEVEL SECURITY;

--
-- Name: cirtscheduler; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE cirtscheduler ENABLE ROW LEVEL SECURITY;

--
-- Name: compiletest; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE compiletest ENABLE ROW LEVEL SECURITY;

--
-- Name: boottest consumer_view; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY consumer_view ON boottest FOR SELECT TO consumer USING (((owner = ("current_user"())::text) OR (owner = 'consumer'::text)));


--
-- Name: compiletest consumer_view; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY consumer_view ON compiletest FOR SELECT TO consumer USING (((owner = ("current_user"())::text) OR (owner = 'consumer'::text)));


--
-- Name: cyclictest consumer_view; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY consumer_view ON cyclictest FOR SELECT TO consumer USING (((owner = ("current_user"())::text) OR (owner = 'consumer'::text)));


--
-- Name: git consumer_view; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY consumer_view ON git FOR SELECT TO consumer USING (((owner = ("current_user"())::text) OR (owner = 'consumer'::text)));


--
-- Name: histogram consumer_view; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY consumer_view ON histogram FOR SELECT TO consumer USING (((owner = ("current_user"())::text) OR (owner = 'consumer'::text)));


--
-- Name: cirtscheduler consumer_view; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY consumer_view ON cirtscheduler FOR SELECT TO consumer USING (((owner = ("current_user"())::text) OR (owner = 'consumer'::text)));


--
-- Name: cyclictest; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE cyclictest ENABLE ROW LEVEL SECURITY;

--
-- Name: git; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE git ENABLE ROW LEVEL SECURITY;

--
-- Name: histogram; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE histogram ENABLE ROW LEVEL SECURITY;

--
-- Name: cirtscheduler jenkins_all; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY jenkins_all ON cirtscheduler FOR ALL TO jenkins USING (true) WITH CHECK (true);


--
-- Name: cirtbranch jenkins_all; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY jenkins_all ON cirtbranch FOR ALL TO jenkins USING (true) WITH CHECK (true);


--
-- Name: boottest jenkins_all; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY jenkins_all ON boottest FOR ALL TO jenkins USING (true) WITH CHECK (true);


--
-- Name: compiletest jenkins_all; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY jenkins_all ON compiletest FOR ALL TO jenkins USING (true) WITH CHECK (true);


--
-- Name: cyclictest jenkins_all; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY jenkins_all ON cyclictest FOR ALL TO jenkins USING (true) WITH CHECK (true);


--
-- Name: git jenkins_all; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY jenkins_all ON git FOR ALL TO jenkins USING (true) WITH CHECK (true);


--
-- Name: histogram jenkins_all; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY jenkins_all ON histogram FOR ALL TO jenkins USING (true) WITH CHECK (true);


--
-- Name: minavgmax jenkins_all; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY jenkins_all ON minavgmax FOR ALL TO jenkins USING (true) WITH CHECK (true);


--
-- Name: minavgmax; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE minavgmax ENABLE ROW LEVEL SECURITY;

--
-- Name: public; Type: ACL; Schema: -; Owner: postgres
--

GRANT ALL ON SCHEMA public TO PUBLIC;


--
-- Name: boottest; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE boottest TO jenkins;


--
-- Name: boottest.id; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(id) ON TABLE boottest TO consumer;


--
-- Name: boottest.cmdline; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(cmdline) ON TABLE boottest TO consumer;


--
-- Name: boottest.pass; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(pass) ON TABLE boottest TO consumer;


--
-- Name: boottest.compiletest_id; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(compiletest_id) ON TABLE boottest TO consumer;


--
-- Name: boottest.target_id; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(target_id) ON TABLE boottest TO consumer;


--
-- Name: boottest.bootdate; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(bootdate) ON TABLE boottest TO consumer;


--
-- Name: boottest_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,USAGE ON SEQUENCE boottest_id_seq TO jenkins;


--
-- Name: compiletest; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE compiletest TO jenkins;


--
-- Name: compiletest.id; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(id) ON TABLE compiletest TO consumer;


--
-- Name: compiletest.custom_commit; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(custom_commit) ON TABLE compiletest TO consumer;


--
-- Name: compiletest.defconfig; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(defconfig) ON TABLE compiletest TO consumer;


--
-- Name: compiletest.overlay; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT("overlay") ON TABLE compiletest TO consumer;


--
-- Name: compiletest.pass; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(pass) ON TABLE compiletest TO consumer;


--
-- Name: compiletest.cirtscheduler_id; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(cirtscheduler_id) ON TABLE compiletest TO consumer;


--
-- Name: compiletest.configname; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(configname) ON TABLE compiletest TO consumer;


--
-- Name: compiletest.arch; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(arch) ON TABLE compiletest TO consumer;


--
-- Name: compiletest.buildcmd; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(buildcmd) ON TABLE compiletest TO consumer;


--
-- Name: cirtbranch; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE cirtbranch TO jenkins;


--
-- Name: cirtbranch.id; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(id) ON TABLE cirtbranch TO consumer;


--
-- Name: cirtbranch.testbranch; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(testbranch) ON TABLE cirtbranch TO consumer;


--
-- Name: cirtbranch.commit; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(commit) ON TABLE cirtbranch TO consumer;


--
-- Name: cirtbranch.cirtscheduler_id; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(cirtscheduler_id) ON TABLE cirtbranch TO consumer;


--
-- Name: cirtscheduler; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE cirtscheduler TO jenkins;


--
-- Name: cirtscheduler.id; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(id) ON TABLE cirtscheduler TO consumer;


--
-- Name: cirtscheduler.branch; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(branch) ON TABLE cirtscheduler TO consumer;


--
-- Name: cirtscheduler.timestamp; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT("timestamp") ON TABLE cirtscheduler TO consumer;


--
-- Name: cirtscheduler.tags_id; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(tags_id) ON TABLE cirtscheduler TO consumer;


--
-- Name: cirtscheduler.pass; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(pass) ON TABLE cirtscheduler TO consumer;


--
-- Name: cirtscheduler.processing; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(processing) ON TABLE cirtscheduler TO consumer;


--
-- Name: cirtscheduler_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,USAGE ON SEQUENCE cirtscheduler_id_seq TO jenkins;


--
-- Name: compiletest_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,USAGE ON SEQUENCE compiletest_id_seq TO jenkins;


--
-- Name: cyclictest; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE cyclictest TO jenkins;


--
-- Name: cyclictest.id; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(id) ON TABLE cyclictest TO consumer;


--
-- Name: cyclictest.description; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(description) ON TABLE cyclictest TO consumer;


--
-- Name: cyclictest.duration; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(duration) ON TABLE cyclictest TO consumer;


--
-- Name: cyclictest.interval; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT("interval") ON TABLE cyclictest TO consumer;


--
-- Name: cyclictest.min; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(min) ON TABLE cyclictest TO consumer;


--
-- Name: cyclictest.avg; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(avg) ON TABLE cyclictest TO consumer;


--
-- Name: cyclictest.max; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(max) ON TABLE cyclictest TO consumer;


--
-- Name: cyclictest.boottest_id; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(boottest_id) ON TABLE cyclictest TO consumer;


--
-- Name: cyclictest.pass; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(pass) ON TABLE cyclictest TO consumer;


--
-- Name: cyclictest.threshold; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(threshold) ON TABLE cyclictest TO consumer;


--
-- Name: cyclictest.testscript; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(testscript) ON TABLE cyclictest TO consumer;


--
-- Name: cyclictest.owner; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(owner) ON TABLE cyclictest TO consumer;


--
-- Name: target; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE target TO consumer;
GRANT ALL ON TABLE target TO jenkins;


--
-- Name: cyc_target; Type: ACL; Schema: public; Owner: consumer
--

GRANT ALL ON TABLE cyc_target TO jenkins;


--
-- Name: cyclictest_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,USAGE ON SEQUENCE cyclictest_id_seq TO jenkins;


--
-- Name: detail; Type: ACL; Schema: public; Owner: consumer
--

GRANT ALL ON TABLE detail TO jenkins;


--
-- Name: git; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE git TO jenkins;


--
-- Name: git.id; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(id) ON TABLE git TO consumer;


--
-- Name: git.path; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(path) ON TABLE git TO consumer;


--
-- Name: git.public; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(public) ON TABLE git TO consumer;


--
-- Name: git.httprepo; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(httprepo) ON TABLE git TO consumer;


--
-- Name: git_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,USAGE ON SEQUENCE git_id_seq TO jenkins;


--
-- Name: histogram; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE histogram TO jenkins;


--
-- Name: histogram.id; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(id) ON TABLE histogram TO consumer;


--
-- Name: histogram.thread; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(thread) ON TABLE histogram TO consumer;


--
-- Name: histogram.latency; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(latency) ON TABLE histogram TO consumer;


--
-- Name: histogram.count; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(count) ON TABLE histogram TO consumer;


--
-- Name: histogram.cyclictest_id; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(cyclictest_id) ON TABLE histogram TO consumer;


--
-- Name: histogram_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,USAGE ON SEQUENCE histogram_id_seq TO jenkins;


--
-- Name: label; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE label TO consumer;
GRANT ALL ON TABLE label TO jenkins;


--
-- Name: kbuild; Type: ACL; Schema: public; Owner: consumer
--

GRANT ALL ON TABLE kbuild TO jenkins;


--
-- Name: label_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,USAGE ON SEQUENCE label_id_seq TO jenkins;


--
-- Name: minavgmax; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE minavgmax TO jenkins;


--
-- Name: minavgmax.thread; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(thread) ON TABLE minavgmax TO consumer;


--
-- Name: minavgmax.cyclictest_id; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(cyclictest_id) ON TABLE minavgmax TO consumer;


--
-- Name: minavgmax.min; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(min) ON TABLE minavgmax TO consumer;


--
-- Name: minavgmax.avg; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(avg) ON TABLE minavgmax TO consumer;


--
-- Name: minavgmax.max; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT(max) ON TABLE minavgmax TO consumer;


--
-- Name: tags; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE tags TO consumer;
GRANT ALL ON TABLE tags TO jenkins;


--
-- Name: overview; Type: ACL; Schema: public; Owner: consumer
--

GRANT ALL ON TABLE overview TO jenkins;


--
-- Name: tags_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,USAGE ON SEQUENCE tags_id_seq TO jenkins;


--
-- Name: target_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,USAGE ON SEQUENCE target_id_seq TO jenkins;


--
-- Name: targetboot; Type: ACL; Schema: public; Owner: consumer
--

GRANT ALL ON TABLE targetboot TO jenkins;


--
-- Name: targets; Type: ACL; Schema: public; Owner: consumer
--

GRANT ALL ON TABLE targets TO jenkins;


--
-- PostgreSQL database dump complete
--

--
-- Add mantatory data entries for CI-RT Jenkins
--

COPY git (id, path, public, httprepo, owner) FROM stdin;
0	git path	f	http path	intern
\.

COPY tags (id, git_id, commit, name) FROM stdin;
0	0	0	dummy
\.
